version: "3.9"
services:
  db:
    image: 'postgres:14-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    depends_on:
      - 'db'
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - PORT=3000
volumes:
  postgres: